version: '3'

services:
  web:
    build: .
    command: >
      sh -c "echo  &&
             echo Наш сайт по ссылке http://localhost:8000/ &&
             echo  &&
             python manage.py runserver 0.0.0.0:8000 &&
             cd ./other/static_src &&
             npm run dev"
    ports:
      - "8000:8000"
    volumes:
      - ./KINOLIB:/KINOLIB