version: '3'

x-app: &default-app
  build:
    context: "."
  volumes:
    - ./KINOLIB:/KINOLIB
  restart: "unless-stopped"


services:
  web:
    <<: *default-app
    command: >
      sh -c "echo  &&
             echo Наш сайт по ссылке http://localhost:8000/ &&
             echo  &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  tailwind:
    <<: *default-app
    command:  >
      sh -c "cd ./other/static_src &&
             npm i &&
             npm run dev
             "

    
    
    restart: always
    tty: true

