# Generated by Django 5.0.4 on 2024-05-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
